events {
    #how many connections to handle at a time 
    worker_connections 1024;
}
http {
    upstream auth_service {
        least_conn;
        server auth-service:8001;
        keepalive 32;
    }
    
#    upstream weather_service {
#        least_conn;
#        server weather-service:8002;
#        keepalive 32;
#    }
#
#    upstream alert_service {
#        least_conn;
#        server alert-service:8003;
#        keepalive 32;
#    }
#    
#    upstream notification_service {
#        least_conn;
#        server notification-service:8004;
#        keepalive 32;
#    }
    

    include /etc/nginx/conf.d/*.conf;
}