events {
    #how many connections to handle at a time 
    worker_connections 1024;
}
http {
    upstream auth_service {
        server auth-service:8001;
    }
    
    upstream weather_service {
        server weather-service:8002;
    }

    upstream alert_service {
        server alert-service:8003;
    }
    
    upstream notification_service {
        server notification-service:8004;
    }
    

    include /etc/nginx/conf.d/*.conf;
}